spring:
  application:
    name: app-cent
  datasource:
    url: jdbc:h2:mem:todolist
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
app-cent:
  app:
    jwtSecret: ${JWT_SECRET:secret-local}
    jwtExpirationMs: ${JWT_EXPIRATION_IN_MS:6000000}

server:
  port: 8082

logging:
  level:
     root: DEBUG

